### ISSUE TITLE
Playlist (.m3u) in MPD database causes `ListAllIn` to fail

### ISSUE THREAD

**Issue by Bobo1239** [elomatreb/mpd_client#11]
If a playlist is present in the MPD database (e.g. a .m3u file) then issuing a `ListAllIn` command results in the following error: `InvalidTypedResponse(TypedResponseError { field: "file", kind: UnexpectedField("playlist") })`.

This probably also affects other commands? Not sure whether this is something people using MPD usually do. (I personally wouldn't but this happened when throwing MPD against an unorganized collection.)

**Comment by elomatreb** [comment]
Weird. The [docs](https://mpd.readthedocs.io/en/latest/protocol.html#command-listall) lead me to assume that only directories and songs would be returned. I'll make it ignore these entries as well.

**Comment by Bobo1239** [comment]
Works perfectly. Thanks for the quick fix!

**Comment by elomatreb** [comment]
I've pushed crate version 0.7.4 which includes this fix.
