### ISSUE TITLE
Add support for `sticker` commands

### ISSUE THREAD

**Issue by JakeStanger** [elomatreb/mpd_client#13]
https://mpd.readthedocs.io/en/latest/protocol.html#stickers

I've started work on this myself but wanted to log it here for the sake of completion or in case you have any opinions. 

As far as I can tell, the `sticker` command is the only one in the protocol to have subcommands in this fashion. It seems a bit silly/fiddly to add a dedicated `commands::Sticker` command, so instead I'm opting to go for `commands::StickerGet`, `commands::StickerGet`, etc.

I'll get a draft PR open once things are in a semi-decent state.

**Comment by elomatreb** [comment]
I agree, dedicated commands would be the right approach. If you want to implement it, feel free.
