### ISSUE TITLE
Added replay_gain_mode and replay_gain_status

### ISSUE THREAD

**Issue by kholthaus** [elomatreb/mpd_client#19]
Please see attached for a path that introduces support for replay_gain_status and replay_gain_mode commands. Not exhaustively tested, and I did not include new tests.
[replay_gain.tar.gz](https://github.com/elomatreb/mpd_client/files/13125492/replay_gain.tar.gz)

**Comment by elomatreb** [comment]
Hi, thanks for the patch. Since I have to apply this patch manually and commit it myself, how would you prefer to be credited for your contribution? If you provide me with an email address, I can add it to the commit as a co-author.

**Comment by kholthaus** [comment]
Thanks for the offer - no credit necessary. :) Glad to give back a little bit - very much appreciate the work you've put in to create the crate in the first place!

**Comment by elomatreb** [comment]
I just published crate version 1.3.0 which includes this feature.
