### ISSUE TITLE
Update ahash version to above 0.8.9

### ISSUE THREAD

**Issue by eternalfrustation** [elomatreb/mpd_client#23]
This package fails to build on the latest nightly due to an older version of ahash. Updating ahash to above 0.8.9 should fix it

**Comment by elomatreb** [comment]
Do you want a release that includes this change? When the library is used as a dependency, cargo ignores the lockfile and should have picked ahash 0.8.9 automatically.

**Comment by eternalfrustation** [comment]
In my case, when i tried to compile mpd_client, cargo picked ahash 0.8.7 on the current nightly [cargo 1.78.0-nightly (194a60b29 2024-02-21)], probably because that was specified in the Cargo.toml in here.

**Comment by eternalfrustation** [comment]
I guess i need a release to remove the patch section my Cargo.toml

**Comment by elomatreb** [comment]
I published mpd_client v1.4.1 which includes this.
