### ISSUE TITLE
Add nicer List command implementation

### ISSUE THREAD

**Issue by elomatreb** [elomatreb/mpd_client#5]
Should actually parse groupings.

**Comment by cassava** [comment]
What kind of groupings do you mean here? Things like albums or is this something else?

**Comment by elomatreb** [comment]
This is about the optional `group` argument offered by the `list` command: https://www.musicpd.org/doc/html/protocol.html#command-list

Currently a response to this shows up as a flat list of `(tag, value)` pairs, when ideally it should be more "tree-shaped" to recognize the grouped items. I tried to implement this originally but couldn't come up with a convenient API, and left myself this issue as a reminder (but I haven't needed the command since).

**Comment by elomatreb** [comment]
Closed in a920839276241b76468090c309d1e2ab3f326c1f
